[package]
name = "my_first_package"
version = "0.0.1"

[dependencies]
Sui = { local = "/Users/vincentlu/Desktop/sui-learning/sui/crates/sui-framework" }

[addresses]
my_first_package =  "0x0"
sui =  "0000000000000000000000000000000000000002"
