[package]
name = "moveX"
version = "0.0.1"

[dependencies]
Sui = { local = "/Users/lu/Desktop/sui/crates/sui-framework" }

[addresses]
moveX =  "0x0"
sui =  "0000000000000000000000000000000000000002"
